### PR TITLE
token type -> `object`

### PR DESCRIPTION
**Pull request by hemanth**
^

### CODE REVIEW

**Comment by sindresorhus** [comment]
No https://github.com/sindresorhus/gh-got/blob/14a80da6eec3610680655f3b2464420a931892a2/index.js#L26

**Comment by hemanth** [comment]
[this](https://github.com/sindresorhus/gh-got/commit/a0e406ffe74fd09607b911a24c2c61414dca9d53#diff-0730bb7c2e8f9ea2438b52e419dd86c9R38) must be just `token` then?

**Comment by sindresorhus** [comment]
That's the option object, with the `token` option.

**Comment by hemanth** [comment]
Yup, figured it, thanks.  :+1:

**Pull request closed without merging**
