### PR TITLE
Use error message returned from GitHub

### LINKED ISSUE #19: Populate error with information from Github
The Github API returns error information in the body as encoded json, it would be nice to get better error messages by using this information.

e.g.

``` http
HTTP/1.1 400 Bad Request
Content-Length: 35

{"message":"Problems parsing JSON"}
```

currently results in:

``` text
HTTPError: Response code 400 (Bad Request)
```

would be nice to get something like:

``` text
GithubError: Problems parsing JSON (400)
```

### PR DESCRIPTION
**Pull request by kevva**
As discussed in #19, I skipped formatting the errors in the streaming API. Not sure how you want it documented though so any input on that would be helpful.

Also, feels like the tests fails because of some globals leaking out from the serial tests. Have something changed in `ava` regarding the order in which the tests are ran.

---

Fixes #19

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Not sure how you want it documented though so any input on that would be helpful.

Right in the `API` section:

> Errors are improved by using the custom GitHub error messages. Doesn't apply to the stream API.

**Comment by sindresorhus** [comment]
> Also, feels like the tests fails because of some globals leaking out from the serial tests. Have something changed in ava regarding the order in which the tests are ran.

Travis had a security incident, so my tokens got invalidated, including the one used in Travis here.

**Comment by kevva** [comment]
> Right in the API section:

```
Same as [`got`](https://github.com/sindresorhus/got) (including the stream API and aliases), but with some additional options below.

Errors are improved by using the custom GitHub error messages. Doesn't apply to the stream API.
```

`additional options:` -> `additional options below` since a `:` followed by a new, unrelated, sentence looks weird to me.

**Comment by sindresorhus** [comment]
👍

**Pull request merged**
