### PR TITLE
Add homepage

### PR DESCRIPTION
**Pull request by gpedro**

### CODE REVIEW

**Comment by sindresorhus** [comment]
That's not needed. It's inferred by npm based on the `repository` property.

You can see all the normalizations npm does here: https://github.com/npm/normalize-package-data#what-normalization-currently-entails

**Comment by gpedro** [comment]
It is useful when you need to go to the repository easily and quickly
selection_004
selection_005

**Comment by shinnn** [comment]
IMO that should be automatically handled by npmjs.com.

**Comment by sindresorhus** [comment]
Yeah, seems like a npm website bug: https://github.com/npm/newww/issues/1172

**Pull request closed without merging**
